name: test_chat_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  provider: ^6.0.5
  cloud_firestore: ^4.12.2
  intl: ^0.18.1
  emoji_picker_flutter: ^1.6.3
  firebase_storage: ^11.4.1
  photo_manager: ^2.7.2
  image_picker: ^1.0.4
  oktoast: ^3.3.2+1
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  flutter_launcher_icons: ^0.13.1
  file_picker: ^5.2.10
  path_provider: ^2.1.1
  path: ^1.8.3
  better_player: ^0.0.80
  flutter_image_compress: ^2.1.0
  socket_io_client: ^2.0.3+1
  stomp_dart_client: ^1.0.0
  agora_rtc_engine: ^6.2.4
  permission_handler: ^11.0.1
  agora_uikit: ^1.3.7
  http: ^1.1.0
  timeago: ^3.6.0
  custom_pin_keyboard: ^0.0.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/love_icon.jpg"
  min_sdk_android: 21    

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/
  #   - images/a_dot_ham.jpeg


 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
