// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQY0qliO900l238ACgeSX_Ul72FXKnsrs',
    appId: '1:884772479361:web:72b8a47ea36bb940af8880',
    messagingSenderId: '884772479361',
    projectId: 'test-chat-app-c11a9',
    authDomain: 'test-chat-app-c11a9.firebaseapp.com',
    storageBucket: 'test-chat-app-c11a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf88lT8UO0L6B8fZ80HBKfqZovzbOZEoE',
    appId: '1:884772479361:android:7000e235e5a9fe1daf8880',
    messagingSenderId: '884772479361',
    projectId: 'test-chat-app-c11a9',
    storageBucket: 'test-chat-app-c11a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSqvqjDrA1GBJSvhzIM-9sagwLzLjYOZ8',
    appId: '1:884772479361:ios:c965183f1e61cdddaf8880',
    messagingSenderId: '884772479361',
    projectId: 'test-chat-app-c11a9',
    storageBucket: 'test-chat-app-c11a9.appspot.com',
    iosBundleId: 'com.example.testChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSqvqjDrA1GBJSvhzIM-9sagwLzLjYOZ8',
    appId: '1:884772479361:ios:c7e2f7653ac056cfaf8880',
    messagingSenderId: '884772479361',
    projectId: 'test-chat-app-c11a9',
    storageBucket: 'test-chat-app-c11a9.appspot.com',
    iosBundleId: 'com.example.testChatApp.RunnerTests',
  );
}
